### ISSUE TITLE
Don't load fontawesome by default

### ISSUE THREAD

**Issue by aurorasmiles** [tomascordero/safety-exit#2]
Even if icons are disabled, the plugin loads fontawesome by default. 
Ideally the frontend shouldn't load fontawesome if icons are disabled, both for performance and data privacy reasons. 
Optionally it would be great to be able to select a local stylesheet for icons (since we already include a local cached fontawesome version)

**Comment by tomascordero** [comment]
That makes sense to me! I think that should be something easy enough to implement. This plugin has been on my back burner for some time now but I think I may be time to pick it back up!

**Comment by tomascordero** [comment]
Version 1.6.0 which I just released should take care of the security / performance concern! I'll have to take a bigger look at the local stylesheet thing.
